# Platform: LINUX

NVCCFLAGS = --ptxas-options=-v -O3 -DLINUX

APP=pfxsum
OBJECTS = helper.o pfxsum.o pfxsum_host.o pfxsum_naive.o pfxsum_rs.o pfxsum_thrust.o

NVCC = nvcc

%.o : %.cu
	$(NVCC) -c $(NVCCFLAGS) $@ $<

%.o : %.cc
	$(NVCC) -c $(NVCCFLAGS) $@ $<

$(APP): $(OBJECTS)
	$(NVCC) -o $@ $(OBJECTS) $(NVCCFLAGS)

clean:
	rm -f *.exe *.exp *.lib $(APP) $(OBJECTS)
 